import Head from "next/head";
import Link from "next/link";
import { useRive } from '@rive-app/react-canvas';

import { Button } from "~/components/ui/button";


export default function Home() {
  const { rive, RiveComponent } = useRive({
    src: '/map-points.riv',
    autoplay: true,
  });

  return (
    <>
      <Head>
        <title>Adopt Ag | MapDash</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid grid-cols-1 lg:grid-cols-2 items-center h-screen overflow-hidden">
        <div className="px-4 md:px-20">
          <h1 className="leading-snug text-6xl">
              Welcome to<br/>
              <span className="md:text-8xl text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-blue-600">mapDash</span>
          </h1>
          <p className="mt-8 max-w-2xl">
            Whether you&apos;re planning a personal project, brainstorming for a
            community endeavor, or seeking inspiration for real estate
            development, our tool provides the canvas for your
            imagination. Unleash your creative potential today!
          </p>
          <Link href="map">
            <Button className="mt-8">Get Started</Button>
          </Link>
        </div>
        <div className="bg-[#1C48AD] w-full h-[100vh] hidden lg:block">
          <RiveComponent />
        </div>
      </main>
    </>
  );
}