import Head from "next/head";
import Mapbox from "~/components/mapbox";

export default function Map() {
  return (
    <>
      <Head>
        <title>Adopt Ag | MapDash</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full items-center justify-center">
        <Mapbox />
      </main>
    </>
  );
}
